/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import NhanVienTCT.login2;
import NhanVienTCT.quanLiNv;
import javax.swing.JOptionPane;
import mathang.QuanLiMatHang;
import phieumuon.QuanLiPhieuMuon;
import phieunhap.QuanLiPhieuNhap;        
/**
 *
 * @author DELL
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private login2 login;
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public MainForm(login2 lg,Boolean rootPaneCheckingEnabled){
        initComponents();
        this.setLocationRelativeTo(null); // dua form ra giua
        if(lg.getIdPQ().equals("PQ2")){
            lb_QLMH.setVisible(false);
            lb_QLNV.setVisible(false);
            lb_QLPN.setVisible(false);
            btn_QLMH.setVisible(false);
            btn_QLNV.setVisible(false);
            btn_QLPN.setVisible(false);
        }
        this.login = lg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_TenNhom = new javax.swing.JLabel();
        lb_QLNV = new javax.swing.JLabel();
        btn_QLNV = new javax.swing.JButton();
        btn_QLMH = new javax.swing.JButton();
        btn_QLPN = new javax.swing.JButton();
        btn_QLPM = new javax.swing.JButton();
        lb_QLPM = new javax.swing.JLabel();
        lb_QLPN = new javax.swing.JLabel();
        lb_QLMH = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To My Shop");
        setMinimumSize(new java.awt.Dimension(1345, 845));
        setPreferredSize(new java.awt.Dimension(1329, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_TenNhom.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lb_TenNhom.setForeground(new java.awt.Color(255, 255, 51));
        lb_TenNhom.setText("   Nhóm 19 Barber");
        getContentPane().add(lb_TenNhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 506, 290, 40));

        lb_QLNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_QLNV.setForeground(new java.awt.Color(255, 255, 51));
        lb_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/user-group-296 (1).png"))); // NOI18N
        lb_QLNV.setText("Quản lí nhân viên");
        getContentPane().add(lb_QLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 230, 50));

        btn_QLNV.setBackground(new java.awt.Color(255, 255, 255));
        btn_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/tick1.png"))); // NOI18N
        btn_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNVActionPerformed(evt);
            }
        });
        getContentPane().add(btn_QLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 70, -1));

        btn_QLMH.setBackground(new java.awt.Color(255, 255, 255));
        btn_QLMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/tick1.png"))); // NOI18N
        btn_QLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLMHActionPerformed(evt);
            }
        });
        getContentPane().add(btn_QLMH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 70, -1));

        btn_QLPN.setBackground(new java.awt.Color(255, 255, 255));
        btn_QLPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/tick1.png"))); // NOI18N
        btn_QLPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLPNActionPerformed(evt);
            }
        });
        getContentPane().add(btn_QLPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 70, -1));

        btn_QLPM.setBackground(new java.awt.Color(255, 255, 255));
        btn_QLPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/tick1.png"))); // NOI18N
        btn_QLPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLPMActionPerformed(evt);
            }
        });
        getContentPane().add(btn_QLPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 70, -1));

        lb_QLPM.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_QLPM.setForeground(new java.awt.Color(255, 255, 51));
        lb_QLPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/user-group-296 (1).png"))); // NOI18N
        lb_QLPM.setText("Quản lí phiếu mượn");
        getContentPane().add(lb_QLPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 250, 50));

        lb_QLPN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_QLPN.setForeground(new java.awt.Color(255, 255, 51));
        lb_QLPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/user-group-296 (1).png"))); // NOI18N
        lb_QLPN.setText("Quản lí phiếu nhập");
        getContentPane().add(lb_QLPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 250, 50));

        lb_QLMH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_QLMH.setForeground(new java.awt.Color(255, 255, 51));
        lb_QLMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/user-group-296 (1).png"))); // NOI18N
        lb_QLMH.setText("Quản lí mặt hàng");
        getContentPane().add(lb_QLMH, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 230, 50));

        btn_Logout.setBackground(new java.awt.Color(0, 0, 0));
        btn_Logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setText("log out");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 750, -1, -1));

        background.setForeground(new java.awt.Color(204, 204, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/anh_nen_cat_toc.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNVActionPerformed
        new quanLiNv().setVisible(true);
    }//GEN-LAST:event_btn_QLNVActionPerformed

    private void btn_QLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLMHActionPerformed
        // TODO add your handling code here:
        new QuanLiMatHang().setVisible(true);
    }//GEN-LAST:event_btn_QLMHActionPerformed

    private void btn_QLPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLPNActionPerformed
        // TODO add your handling code here:
        new QuanLiPhieuNhap(login.getIdNV()).setVisible(true);
    }//GEN-LAST:event_btn_QLPNActionPerformed

    private void btn_QLPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLPMActionPerformed
        // TODO add your handling code here:
        new QuanLiPhieuMuon(login.getIdNV(),login.getIdPQ()).setVisible(true);
    }//GEN-LAST:event_btn_QLPMActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất?", "Sign out", JOptionPane.YES_NO_OPTION);
        if (choice == 0) {
            setVisible(false);
            new login2().setVisible(true);
        }
        //        dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_QLMH;
    private javax.swing.JButton btn_QLNV;
    private javax.swing.JButton btn_QLPM;
    private javax.swing.JButton btn_QLPN;
    private javax.swing.JLabel lb_QLMH;
    private javax.swing.JLabel lb_QLNV;
    private javax.swing.JLabel lb_QLPM;
    private javax.swing.JLabel lb_QLPN;
    private javax.swing.JLabel lb_TenNhom;
    // End of variables declaration//GEN-END:variables
}
//test
