/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathang;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ThongKeMHHu extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeMHHu
     */
    public ThongKeMHHu() {
        initComponents();
        this.setLocationRelativeTo(null); // can cho form ngay giua 
    }
    
    public ThongKeMHHu(ArrayList<MatHang> mh,ArrayList<LichSuHu> ls) {
        initComponents();
        this.setLocationRelativeTo(null);// can cho form ngay giua
        int tongSL = 0,index = 0;
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        DefaultTableModel model = new DefaultTableModel();
        String a[] = {"       ID", "   Tên mặt hàng", "  Số lượng hư hoặc hết hạn","    Ngày bị hư"};
        model.setColumnIdentifiers(a);
        ArrayList arrRows = new ArrayList();
        for(MatHang temp:mh){
            arrRows.add(temp.getIdMatHang());
            arrRows.add(temp.getTenMatHang());
            arrRows.add(String.valueOf(ls.get(index).getSoLuongHu()));
            arrRows.add(formatter.format(ls.get(index).getNgayHu()));
            tongSL = tongSL + ls.get(index).getSoLuongHu();
            model.addRow(arrRows.toArray());
            index++;
            arrRows.clear();
        }
        this.text_TongCong.setText(String.valueOf(tongSL));
        this.text_TongCong.setEditable(false);
        this.Tb_SPHu.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_TieuDe = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tb_SPHu = new javax.swing.JTable();
        lb_TongCong = new javax.swing.JLabel();
        text_TongCong = new javax.swing.JTextField();
        lb_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống Kê");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_TieuDe.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb_TieuDe.setForeground(new java.awt.Color(153, 0, 0));
        lb_TieuDe.setText("Các sản phẩm đang hư và mỹ phẩm hết hạn");
        getContentPane().add(lb_TieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 73, -1, 40));

        Tb_SPHu.setAutoCreateRowSorter(true);
        Tb_SPHu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Tb_SPHu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "                                   ID", "                                Tên mặt hàng", "                                    Số lượng", "                            Ngày bị hư"
            }
        ));
        Tb_SPHu.setMinimumSize(new java.awt.Dimension(45, 120));
        Tb_SPHu.setPreferredSize(new java.awt.Dimension(225, 120));
        Tb_SPHu.setRowHeight(30);
        jScrollPane2.setViewportView(Tb_SPHu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 990, 200));

        lb_TongCong.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb_TongCong.setForeground(new java.awt.Color(153, 0, 0));
        lb_TongCong.setText("Tổng Cộng: ");
        getContentPane().add(lb_TongCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, 40));

        text_TongCong.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(text_TongCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 140, -1));

        lb_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/thongkehu.jpg"))); // NOI18N
        lb_Background.setPreferredSize(new java.awt.Dimension(1054, 376));
        getContentPane().add(lb_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeMHHu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeMHHu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeMHHu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeMHHu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeMHHu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_SPHu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_Background;
    private javax.swing.JLabel lb_TieuDe;
    private javax.swing.JLabel lb_TongCong;
    private javax.swing.JTextField text_TongCong;
    // End of variables declaration//GEN-END:variables
    
}
