/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phieumuon;

import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mathang.LichSuHu;
import static phieumuon.SuaPhieuMuon.KTinput;

/**
 *
 * @author DELL
 */
public class FormTraDC extends javax.swing.JFrame {

    /**
     * Creates new form ShowCTPN
     */
    private QuanLiPhieuMuon qlpm;
    private DefaultTableModel model;
    private InfoCTPM infomation;
    private ArrayList<Integer> listSLHu = new ArrayList<>();
    private String ngayMuon;
    public InfoCTPM getInfo(){
        return this.infomation;
    }
    
    public FormTraDC() {
        initComponents();
    }

    public FormTraDC(QuanLiPhieuMuon aThis, boolean rootPaneCheckingEnabled,String strDate){
        initComponents();
        this.setLocationRelativeTo(null);
        lb_IDPM.setText("Chi tiết của phiếu trả: " + aThis.getPhieuMuon().getIdPM());
        loadData(aThis,0);
        qlpm = aThis;
        text_SLHu.setVisible(false);
        lb_SLHu.setVisible(false);
        btn_Update.setVisible(false);
        ngayMuon = this.convertStrToStr(strDate);
    }
    
    //convert string dd-mm-yyyy to yyyy-mm-dd
    public String convertStrToStr(String strDD){
        String day,year;
        day = strDD.split("-")[0];
        year = strDD.split("-")[2];
        String strYYYY = year + "-" +strDD.split("-")[1] + "-" + day;
        return strYYYY;
    }
    
    //load du lieu len form
    public void loadData(QuanLiPhieuMuon aThis,int slHu){
        ctphieumuon.ConnectionSQL sqlCTPM = new ctphieumuon.ConnectionSQL();
        String idPM = aThis.getPhieuMuon().getIdPM();
        ArrayList<InfoCTPM> list = sqlCTPM.getListCTPM(idPM);
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // xoa bo noi dung cu cua table
        for (InfoCTPM info : list) {
            Object[] data = {info.getIdmathang(),info.getTenmathang(),info.getSoLuong(),slHu};
            listSLHu.add(slHu);
            model.addRow(data);
        }
    }
    
    //load du lieu len form sau khi update soluonghu
    public void loadData(QuanLiPhieuMuon aThis,int slHu,String idMH){
        ctphieumuon.ConnectionSQL sqlCTPM = new ctphieumuon.ConnectionSQL();
        String idPM = aThis.getPhieuMuon().getIdPM();
        ArrayList<InfoCTPM> list = sqlCTPM.getListCTPM(idPM);
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // xoa bo noi dung cu cua table
        int i = 0;
        for (InfoCTPM info : list) {
            if(info.getIdmathang().equals(idMH)){
                listSLHu.set(i, slHu);
                i++;
            }
            else i++;
        }
        i = 0;
        for (InfoCTPM info : list) {
            Object[] data = {info.getIdmathang(),info.getTenmathang(),info.getSoLuong(),listSLHu.get(i)};
            model.addRow(data);
            i++;
        }
    }
    
    //lay du lieu tu 1 hang cua table
    public InfoCTPM getDataARow(){
        InfoCTPM info = new InfoCTPM();
        int i = jTable1.getSelectedRow();
        info.setIdmathang((String) jTable1.getValueAt(i,0));
        info.setTenmathang((String) jTable1.getValueAt(i,1));
        Object a =  jTable1.getValueAt(i,2);
        info.setSoLuong((int) a);
        return info;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lb_IDPM = new javax.swing.JLabel();
        btn_Submit = new javax.swing.JButton();
        lb_SLHu = new javax.swing.JLabel();
        text_SLHu = new javax.swing.JTextField();
        btn_Reset = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông Tin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "               Mã mặt hàng", "               Tên mặt hàng", "                Số lượng", "                Số lượng hư"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 714, 410));

        lb_IDPM.setBackground(new java.awt.Color(204, 204, 204));
        lb_IDPM.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb_IDPM.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(lb_IDPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 326, 30));

        btn_Submit.setBackground(new java.awt.Color(255, 255, 255));
        btn_Submit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/back.png"))); // NOI18N
        btn_Submit.setText("Submit");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 130, -1));

        lb_SLHu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lb_SLHu.setForeground(new java.awt.Color(255, 255, 0));
        lb_SLHu.setText("Số Lượng Hư");
        getContentPane().add(lb_SLHu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 140, 30));

        text_SLHu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        text_SLHu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_SLHuKeyReleased(evt);
            }
        });
        getContentPane().add(text_SLHu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 130, 40));

        btn_Reset.setBackground(new java.awt.Color(255, 255, 255));
        btn_Reset.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/reset.png"))); // NOI18N
        btn_Reset.setText("Reset");
        btn_Reset.setMinimumSize(new java.awt.Dimension(129, 37));
        btn_Reset.setPreferredSize(new java.awt.Dimension(129, 37));
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 130, 40));

        btn_Update.setBackground(new java.awt.Color(255, 255, 255));
        btn_Update.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/edit.png"))); // NOI18N
        btn_Update.setText("Update");
        btn_Update.setMinimumSize(new java.awt.Dimension(129, 37));
        btn_Update.setPreferredSize(new java.awt.Dimension(129, 37));
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 130, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phieunhap/background_formQL.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //lay ngay gio hien tai
    public java.sql.Date getTime(){
        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);   
        return date;
    }
    
    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        LichSuHu lsh = new LichSuHu();
        LichSuHu lsh1 = new LichSuHu();
        Date date = Date.valueOf(ngayMuon);  
        for(int i = 0;;i++){
            try{
                if(jTable1.getValueAt(i,0) == null){
                    break;
                }
                else if(Integer.parseInt(jTable1.getValueAt(i,3).toString()) != 0){
                    lsh.setIdMatHang(jTable1.getValueAt(i,0).toString());
                    lsh.setSoLuongHu(Integer.parseInt(jTable1.getValueAt(i,3).toString()));
                    lsh.setNgayHu(date);
                    ConnectionSQL sql = new ConnectionSQL();
                    lsh1 = sql.getPK(lsh.getIdMatHang(), ngayMuon);
                    if(lsh1.getIdMatHang() == null){
                        sql.insertSLH(lsh);
                        String updatePM = "update phieumuon set datra = 'True' where idpm = '" +
                                qlpm.getPhieuMuon().getIdPM() + "'";
                        sql.updateSQL(updatePM);
                    }
                    else{
                        int soLuongHu = lsh.getSoLuongHu() + lsh1.getSoLuongHu();
                        String update = "update lichsuhu set soluonghu = '" +
                                soLuongHu + "' where idmathang = '" + lsh1.getIdMatHang() + "' "
                                + "and ngayhu = '" + lsh1.getNgayHu() + "'";
                        sql.updateSQL(update);
                        String updatePM = "update phieumuon set datra = 'True' where idpm = '" +
                                qlpm.getPhieuMuon().getIdPM() + "'";
                        sql.updateSQL(updatePM);
                    }
                }
                else if(Integer.parseInt(jTable1.getValueAt(i,3).toString()) == 0){                    
                    ConnectionSQL sql = new ConnectionSQL();
                    String updatePM = "update phieumuon set datra = 'True' where idpm = '" +
                                qlpm.getPhieuMuon().getIdPM() + "'";
                        sql.updateSQL(updatePM);
                }
            }
            catch(ArrayIndexOutOfBoundsException ex){
                break;
            }
        }
        this.dispose();
        qlpm.loadData();
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void text_SLHuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_SLHuKeyReleased
        // TODO add your handling code here:
        String text = text_SLHu.getText();
        char a = text.charAt(text.length() - 1);
        if(!KTinput(Character.toString(a)) || text_SLHu.getText().equals("0") || text_SLHu.getText().equals(" ")){
            text_SLHu.setText("");
            JOptionPane.showMessageDialog(rootPane, "Bạn chỉ được nhập số lớn hơn 0!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        InfoCTPM info = this.getInfo();
        if(Integer.parseInt(text) > info.getSoLuong()){
            text_SLHu.setText("");
            JOptionPane.showMessageDialog(rootPane, "Đã vượt quá số lượng mượn!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_text_SLHuKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        infomation = this.getDataARow();
        text_SLHu.setVisible(true);
        lb_SLHu.setVisible(true);
        btn_Update.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        listSLHu.removeAll(listSLHu);
        loadData(qlpm, 0);
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        loadData(qlpm,Integer.parseInt(text_SLHu.getText()),this.getDataARow().getIdmathang());
        text_SLHu.setText("");
        text_SLHu.setVisible(false);
        lb_SLHu.setVisible(false);
        btn_Update.setVisible(false);
    }//GEN-LAST:event_btn_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTraDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTraDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTraDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTraDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTraDC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JButton btn_Update;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_IDPM;
    private javax.swing.JLabel lb_SLHu;
    private javax.swing.JTextField text_SLHu;
    // End of variables declaration//GEN-END:variables
}
