/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phieumuon;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class QuanLiPhieuMuon extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiPhieuNhap
     */
    private DefaultTableModel model;   
    private ArrayList<PhieuMuon> dsPhieuMuon;
    private PhieuMuon phieumuon;
    private String idNV;
    private String idPQ;

    public String getIdPQ() {
        return idPQ;
    }
    
    public String getIdNV() {
        return idNV;
    }

    public PhieuMuon getPhieuMuon() {
        return phieumuon;
    }
    
    public QuanLiPhieuMuon() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }
    
    public QuanLiPhieuMuon(String idNV,String idPQ) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idNV = idNV;
        this.idPQ = idPQ;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comb_TimKiem = new javax.swing.JComboBox<>();
        text_TimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Info = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        traButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lí Phiếu Mượn");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comb_TimKiem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        comb_TimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã phiếu mượn", "Mã nhân viên" }));
        comb_TimKiem.setToolTipText("");
        getContentPane().add(comb_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, -1, -1));

        text_TimKiem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        text_TimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_TimKiemKeyReleased(evt);
            }
        });
        getContentPane().add(text_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 53, 513, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "        Mã phiếu mượn", "         Ngày mượn", "           Tên", "      Tình trạng phiếu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 138, 560, 324));

        btn_Info.setBackground(new java.awt.Color(255, 255, 255));
        btn_Info.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/info1.jpg"))); // NOI18N
        btn_Info.setText("Info");
        btn_Info.setMaximumSize(new java.awt.Dimension(125, 37));
        btn_Info.setMinimumSize(new java.awt.Dimension(125, 37));
        btn_Info.setPreferredSize(new java.awt.Dimension(125, 37));
        btn_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 130, -1));

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/them.png"))); // NOI18N
        addButton.setText("Thêm");
        addButton.setToolTipText("Add");
        addButton.setMaximumSize(new java.awt.Dimension(125, 37));
        addButton.setMinimumSize(new java.awt.Dimension(125, 37));
        addButton.setPreferredSize(new java.awt.Dimension(125, 37));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, -1));

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/edit.png"))); // NOI18N
        editButton.setText("Sửa");
        editButton.setToolTipText("Edit");
        editButton.setMaximumSize(new java.awt.Dimension(125, 37));
        editButton.setMinimumSize(new java.awt.Dimension(125, 37));
        editButton.setPreferredSize(new java.awt.Dimension(125, 37));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 130, -1));

        delButton.setBackground(new java.awt.Color(255, 255, 255));
        delButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        delButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/delete2.png"))); // NOI18N
        delButton.setText("Xoá");
        delButton.setToolTipText("Remove");
        delButton.setMaximumSize(new java.awt.Dimension(125, 37));
        delButton.setMinimumSize(new java.awt.Dimension(125, 37));
        delButton.setPreferredSize(new java.awt.Dimension(125, 37));
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });
        getContentPane().add(delButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 130, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/back.png"))); // NOI18N
        backButton.setText("Trở lại");
        backButton.setToolTipText("Remove");
        backButton.setPreferredSize(new java.awt.Dimension(87, 37));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 425, 130, -1));

        traButton1.setBackground(new java.awt.Color(255, 255, 255));
        traButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        traButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathang/edit.png"))); // NOI18N
        traButton1.setText("Trả");
        traButton1.setToolTipText("Edit");
        traButton1.setMaximumSize(new java.awt.Dimension(125, 37));
        traButton1.setMinimumSize(new java.awt.Dimension(125, 37));
        traButton1.setPreferredSize(new java.awt.Dimension(125, 37));
        traButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(traButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 130, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phieumuon/background_formQL.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_TimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_TimKiemKeyReleased
        // TODO add your handling code here:
        int columnIndex = 0;
        String value = (String) comb_TimKiem.getSelectedItem();
        switch (value) {
            case "Mã phiếu mượn":
            columnIndex = 0;
            break;
            case "Mã nhân viên":
            columnIndex = 2;
            break;
        }
        timKiem(columnIndex);
    }//GEN-LAST:event_text_TimKiemKeyReleased

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if(this.getPhieuMuon() == null){
            JOptionPane.showMessageDialog(rootPane, "Phải chọn 1 phiếu mượn để sửa thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        SuaPhieuMuon spm = new SuaPhieuMuon(this,rootPaneCheckingEnabled);
        spm.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        FormPhieuMuon fpm = new FormPhieuMuon(this,rootPaneCheckingEnabled);
        fpm.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        phieumuon = getDataARow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        if(this.getPhieuMuon() == null){
            JOptionPane.showMessageDialog(rootPane, "Phải chọn 1 phiếu mượn để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        int option = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắn chắn muốn xóa phiếu mượn này?", "Cảnh báo",JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION){
            ConnectionSQL sql = new ConnectionSQL();
            String idPM = phieumuon.getIdPM();
            try{
                sql.deleteSQL(idPM);
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Đã xảy ra lỗi khi xóa phiếu !", "Lỗi", JOptionPane.ERROR_MESSAGE);                        
            }
            loadData();
            JOptionPane.showMessageDialog(rootPane, "Phiếu mượn đã xóa thành công!", "Message", JOptionPane.INFORMATION_MESSAGE);
        }            
    }//GEN-LAST:event_delButtonActionPerformed

    private void btn_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InfoActionPerformed
        // TODO add your handling code here:
        if(this.getPhieuMuon() == null){
            JOptionPane.showMessageDialog(rootPane, "Phải chọn 1 phiếu mượn để xem thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        ShowCTPM info = new ShowCTPM(this, rootPaneCheckingEnabled);
        info.setVisible(true);
    }//GEN-LAST:event_btn_InfoActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    
    private void traButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traButton1ActionPerformed
        // TODO add your handling code here:
        if(this.getPhieuMuon() == null){
            JOptionPane.showMessageDialog(rootPane, "Phải chọn 1 phiếu mượn để trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        ConnectionSQL sql = new ConnectionSQL();
        if(sql.getDaTra(this.getPhieuMuon().getIdPM())){
            JOptionPane.showMessageDialog(rootPane, "Phiếu mượn này đã trả!", "Lỗi", JOptionPane.ERROR_MESSAGE);            
            return; 
        }
        String strDate = this.jTable1.getValueAt(this.jTable1.getSelectedRow(),1).toString();
        FormTraDC tra = new FormTraDC(this, rootPaneCheckingEnabled,strDate);
        tra.setVisible(true);
    }//GEN-LAST:event_traButton1ActionPerformed
    
    //tim kiem theo ma hoac ten
    private void timKiem(int columnIndex) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(String.format("(?i)%s", text_TimKiem.getText()), columnIndex));
    }
    
    //load du lieu len table
    public void loadData(){
        ConnectionSQL sql = new ConnectionSQL();
        //test tinh nang khi co user se xu li
//        String idpq = "PQ1",idnv = "NV3";
        SimpleDateFormat format1 = new SimpleDateFormat("dd-MM-yyyy");
        dsPhieuMuon =  sql.getListPM();        
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // xoa bo noi dung cu cua table
        if(idPQ.equals("PQ2")){
            for (PhieuMuon pm : dsPhieuMuon) {
                if(pm.getIdNV().equals(idNV)){
                    String ten = null;
                    try {
                        String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_DCMPTCT;user=sa;password=123";
                        java.sql.Connection conn = DriverManager.getConnection(dbURL);
                        Statement stmt = conn.createStatement();
                        String select = "select ten from nhanvien where idnv = '" + pm.getIdNV() +"'";
                        ResultSet rs = stmt.executeQuery(select);
                        while(rs.next()){
                            ten = rs.getString("ten");
                        }   
                    } catch (SQLException ex) {
                        System.err.println("Cannot connect database, " + ex);
                    }
                String daTra;
                if(pm.isDaTra()) daTra = "Đã trả";
                else daTra = "Chưa trả";
                Object[] data = {pm.getIdPM(),format1.format(pm.getNgayMuon()),ten,daTra}; 
                    model.addRow(data);
                }
            }
        }
        else{
            for (PhieuMuon pm : dsPhieuMuon) {
                String ten = null;
                try {
                    String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_DCMPTCT;user=sa;password=123";
                    java.sql.Connection conn = DriverManager.getConnection(dbURL);
                    Statement stmt = conn.createStatement();
                    String select = "select ten from nhanvien where idnv = '" + pm.getIdNV() +"'";
                    ResultSet rs = stmt.executeQuery(select);
                    while(rs.next()){
                        ten = rs.getString("ten");
                    }   
                } catch (SQLException ex) {
                    System.err.println("Cannot connect database, " + ex);
                }
                String daTra;
                if(pm.isDaTra()) daTra = "Đã trả";
                else daTra = "Chưa trả";
                Object[] data = {pm.getIdPM(),format1.format(pm.getNgayMuon()),ten,daTra};                 
                model.addRow(data);
            }
        }
    }
    
    //lay du lieu tu 1 hang cua table
    public PhieuMuon getDataARow(){
        PhieuMuon pm = new PhieuMuon();
        try {
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
            int i = jTable1.getSelectedRow();
            pm.setIdPM((String) jTable1.getValueAt(i,0));
            pm.setNgayMuon(format1.parse((String) jTable1.getValueAt(i,1)));
            pm.setIdNV((String) jTable1.getValueAt(i,2));
        } catch (ParseException ex) {
            Logger.getLogger(QuanLiPhieuMuon.class.getName()).log(Level.SEVERE, null, ex);
        }
        return pm;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiPhieuMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_Info;
    private javax.swing.JComboBox<String> comb_TimKiem;
    private javax.swing.JButton delButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_TimKiem;
    private javax.swing.JButton traButton1;
    // End of variables declaration//GEN-END:variables
}
