/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVienTCT;

//import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
//import javafx.animation.KeyValue;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import sun.security.rsa.RSACore;

/**
 *
 * @author Admin
 */
public class quanLiNv extends javax.swing.JFrame {
    
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433; databaseName=QL_DCMPTCT";
    String user ="sa";
    String password = "123";
  
    // hien thi tu jtable sql sang txtfeild
   Vector rowheader=null;
   private Connection con3=null;
   DefaultTableModel model= null;
   Connection cn=null;
   
   private Connection getConnection(){
       try {
           
           Class.forName(driver);
           Connection con2=DriverManager.getConnection(url,user,password);
           
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this,e.getMessage());
       }
       return cn;
       
   }
    public quanLiNv() {    
        initComponents();
        this.setLocationRelativeTo(null);
        rowheader= new Vector();
        rowheader.add("Mã nhân viên");
        rowheader.add("Họ");
        rowheader.add("Tên");
        rowheader.add("Giới tính");
        rowheader.add("Địa chỉ");
        
        model = new DefaultTableModel(rowheader,0);
        jTable1_nhanvien.setModel(model);
        txtmanv.setEditable(false); // khong cho sua idnv trong phan search
        
        
        show_nv();
    }
    
    private void listnv(){
        Vector rowdata=null;
        try {
            
            String query3="select * from nhanvien";
            con3=getConnection();
            Statement st=con3.createStatement();
            ResultSet rs=st.executeQuery(query3);
            while(rs.next()){
                rowdata=new Vector();
                rowdata.add(rs.getString(1));
                rowdata.add(rs.getString(2));
                rowdata.add(rs.getString(3));
                rowdata.add(rs.getString(4));
                rowdata.add(rs.getString(5));
                model.addRow(rowdata);
                
            }
            st.close();
            con3.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }
    
    
    
    public ArrayList<nhanvien> nvList(){
    ArrayList<nhanvien> nvList= new ArrayList<>();
        try {
            Class.forName(driver);
             Connection con1 = DriverManager.getConnection(url,user,password);
            String query1="SELECT * FROM nhanvien";
            Statement st = con1.createStatement();
            ResultSet rs = st.executeQuery(query1);
            nhanvien nv;
            while(rs.next()){
            nv = new nhanvien(rs.getString("idnv"), rs.getString("ho"), rs.getString("ten") ,rs.getString("gioitinh"), rs.getString("diachi"));
            nvList.add(nv);
        }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        return nvList;  
}
    
    public void show_nv(){
        ArrayList<nhanvien> list = nvList();
        DefaultTableModel model= (DefaultTableModel)jTable1_nhanvien.getModel();
       Object[] row = new Object[5];
       for(int i=0;i<list.size();i++){
           row[0]= list.get(i).getIdnv();
           row[1]= list.get(i).getHo();
           row[2]= list.get(i).getTen();
           row[3]= list.get(i).getGioitinh();
           row[4]= list.get(i).getDiachi();
           model.addRow(row);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_nhanvien = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtgioitinh = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí nhân viên");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1_nhanvien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTable1_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ", "Tên", "Giới Tính", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_nhanvien.setRowHeight(30);
        jTable1_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_nhanvien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 468, 518));

        btnadd.setBackground(new java.awt.Color(51, 255, 0));
        btnadd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/add-user-302 (1).png"))); // NOI18N
        btnadd.setText("Insert");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 11, 116, 48));

        btndelete.setBackground(new java.awt.Color(255, 51, 51));
        btndelete.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/user-logout-304 (2).png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 11, 135, 48));

        btnupdate.setBackground(new java.awt.Color(255, 153, 0));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/convert-3213.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 430, 130, 39));

        btnclose.setBackground(new java.awt.Color(0, 0, 0));
        btnclose.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 480, 94, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Mã NV");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 122, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Họ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 179, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Tên");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 251, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Giới tính");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 312, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Địa chỉ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 381, -1, -1));

        txtmanv.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanvActionPerformed(evt);
            }
        });
        getContentPane().add(txtmanv, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 122, 157, -1));

        txtho.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 179, 157, -1));

        txtten.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 247, 157, -1));

        txtgioitinh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txtgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 309, 157, -1));

        txtdiachi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 378, 157, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Search( Mã NV )");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 70, -1, -1));

        txtsearch.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 157, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/QLNV_background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        new addUser().setVisible(true);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        
        int opt =JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không","Xóa",JOptionPane.YES_NO_OPTION);
        if(opt==0){
         
            
        int i = jTable1_nhanvien.getSelectedRow();
        String idnvtam=((String) jTable1_nhanvien.getValueAt(i,0));
        if(idnvtam.equals("NV0001")){
            JOptionPane.showMessageDialog(this,"không được phép xóa admin");
            return;
        }
        
            
            
            
        try {
            Class.forName(driver);
            Connection con= DriverManager.getConnection(url,user,password);
            int row=jTable1_nhanvien.getSelectedRow();
            String value=(jTable1_nhanvien.getModel().getValueAt(row,0).toString());
            String query1=" select username from userCH where idnv='"+value+"'";
            PreparedStatement ps1=con.prepareCall(query1);
            ResultSet rs = ps1.executeQuery(); // khi nao dung select thi resultset 
            String value1 = null;
            while(rs.next()){
                value1 =rs.getString("username"); // lay chuoi username ra de delete user truoc sau do delete nhan vien
            }
            String query2=" DELETE FROM userCH where username='"+value1+"'";
            PreparedStatement ps2=con.prepareCall(query2);
            ps2.executeUpdate();
            String query =" DELETE FROM nhanvien where idnv='" +value+ "'";
            PreparedStatement ps=con.prepareStatement(query); // Nó được sử dụng để thực hiện truy vấn tham số.
            ps.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)jTable1_nhanvien.getModel();
            model.setRowCount(0);
            show_nv();
            JOptionPane.showMessageDialog(null,"Delete Seccessfully");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }
        
        
        
    }//GEN-LAST:event_btndeleteActionPerformed

    
    // update du lieu tu feild sang table 
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        
        try {
             Class.forName(driver);
            Connection con= DriverManager.getConnection(url,user,password);
            String value = txtmanv.getText();
            String query="update nhanvien set idnv=?,ho=?,ten=?,gioitinh=?,diachi=? where idnv='" +value+ "'";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,txtmanv.getText());
            pst.setString(2,txtho.getText());
            pst.setString(3,txtten.getText());
            pst.setString(4,txtgioitinh.getText());
            pst.setString(5,txtdiachi.getText());
            pst.executeUpdate();
            DefaultTableModel model= (DefaultTableModel)jTable1_nhanvien.getModel();
            model.setRowCount(0);
            show_nv();
            JOptionPane.showMessageDialog(null,"Update Sucessfully");  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanvActionPerformed
// xet click table de hien thi qua file txt field
    private void jTable1_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_nhanvienMouseClicked
        
        int index=jTable1_nhanvien.getSelectedRow();
        txtmanv.setText((String)(model.getValueAt(index, 0)));
         txtho.setText((String)model.getValueAt(index, 1));
          txtten.setText((String)model.getValueAt(index, 2));
           txtgioitinh.setText((String)model.getValueAt(index, 3));
            txtdiachi.setText((String)model.getValueAt(index, 4));
    }//GEN-LAST:event_jTable1_nhanvienMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        try {
            
            Class.forName(driver);
            Connection con= DriverManager.getConnection(url,user,password);
            String sql ="select * from nhanvien where idnv=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,txtsearch.getText().trim());        
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String setid = rs.getString("idnv");
                txtmanv.setText(setid);
         
                
                String setho = rs.getString("ho");
                txtho.setText(setho); 
                
                String setten = rs.getString("ten");
                txtten.setText(setten);
                
                String setgioitinh = rs.getString("gioitinh");
                txtgioitinh.setText(setgioitinh);
                
                String setdiachi = rs.getString("diachi");
                txtdiachi.setText(setdiachi);
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }                                                    
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLiNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLiNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLiNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLiNv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLiNv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_nhanvien;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtgioitinh;
    private javax.swing.JTextField txtho;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables

    private void While(boolean next) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
